### ISSUE TITLE
Could you add a license to this repo?

### ISSUE THREAD

**Issue by legut2** [bylexus/fparse#2]
Hi, could you please assign a standardized license to this project? I was considering using it but there seems to be a lack of a license in the repo. If I missed it, could you please point it out to me?

**Comment by bylexus** [comment]
Hi,

You're right, the project has no license as of today. I herewith allow you to use the library in any form you want, commercially or not. Just add a reference to me in your project reference somewhere, thank you.

**Comment by legut2** [comment]
Thanks.
