### ISSUE TITLE
Syntax error with `-z+t`

### ISSUE THREAD

**Issue by valter1977** [bylexus/fparse#22]
Hello,
For some reason, the parser doesn't like expression `-z+t`. However, `-z` is fine and `z+t` also works.

**Comment by bylexus** [comment]
Hi,
Thanks, I will investigate in this. In the meantime, does `(-z)+t` work?

**Comment by valter1977** [comment]
Yes, `(-z)+t` works indeed. Which is expected, as `-z` alone also works.

**Comment by bylexus** [comment]
I have fixed the issue in Version 2.0.2, hopefull this works for you now.
