### ISSUE TITLE
Support for binary operations ?

### ISSUE THREAD

**Issue by Necmttn** [bylexus/fparse#27]
I would like to use fparse to create binary cases to execute like
```
x + y < z
x > y
x >= z
x + y + z = 10
etc 
```

is there a way to extend this functionality?

**Comment by bylexus** [comment]
Those are boolean expressions, which do not evaluate in a number result. You can however register your own functions to achieve this, e.g. like this:

```
const fObj = new Formula('lessThan(x+y, z)');
fObj.lessThan = (a, b) => a < b ? 1 : 0;
let result = fObj.evaluate({x: 1, y: 2: z: 4}); // => 1
```

**Comment by bylexus** [comment]
Docu Pointer: <https://fparse.alexi.ch/#using-user-defined-functions>

**Comment by Necmttn** [comment]
gotcha, thank you
